### ISSUE TITLE
print String

### ISSUE THREAD

**Issue by kang2k10** [notisrac/SH1106Lib#1]
in my sketch, i use
String menu="Test";

display.print(menu);

but error: no matching function for call to 'SH1106Lib::print(String&)'
How i print from string ?

**Comment by notisrac** [comment]
The aim of this library is to keep its footprint as small as possible. Arduino's string lib is quite large, so support for it has been excluded from [TinyPrint](https://github.com/notisrac/TinyPrint), thus from this library as well. You can of course use char arrays, numbers, flash strings, etc.
In your case use juse use a [char array](https://www.arduino.cc/reference/en/language/variables/data-types/string/) or a [flash string](https://www.arduino.cc/reference/en/language/variables/utilities/progmem/).

(Also it is a good practice to not use the built in String lib, but use char arrays instead - even, it is a bit more complicated.)

**Comment by khanmaum** [comment]
Try  display.print(menu.c_str());
