### ISSUE TITLE
can't print int variable values

### ISSUE THREAD

**Issue by piflixe** [notisrac/SH1106Lib#2]
Hi there,

I hope this is not completely trivial: I am trying to print the value of an int (or long) variable. I used the text example and thought it the display.print(); expected a string. So I tried casting the variable to char or string and even converted it using the String command. But none seems to work.

Could someone please post a small example of how to work with variables?

Thank you!

**Comment by notisrac** [comment]
Hi,

You should not do any conversion, just pass in the variable.

**Comment by piflixe** [comment]
Dear @notisrac thanks for your reply. I figured it our with the help of my colleague : I have to set
TP_NUMBERS 1
And then it works as expected.
